sudo: required
services:
  - docker
before_install:
  - docker pull nimlang/nim
script:
  - docker run nimlang/nim nim --version
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "apt-get update && apt-get install -y libgl1-mesa-glx && nimble install -dy && nimble test"

